project:
  type: website
  output-dir: docs

website:
  title: "Morris-Sibaja"
  favicon: images/hackerman.png
  navbar:
    title: false
    logo: images/hackerman.png
    logo-alt: "IMS logo - a triangle containg an i, m, and s"
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog
      - href: resume/IMS_Resume.pdf
        text: Resume
      - href: about.qmd
        text: About
      - href: https://imsibaja.github.io/applied-python-portfolio-2022/
        text: Applied Python Portfolio
        
  page-footer: 
    background: dark
    left: Copyright 2024, Ian Morris-Sibaja
    right: This website is built with {{< fa brands github-alt title="the alt octocat github icon">}}
format:
  html:
    theme: 
      - styles.scss
    mainfont: Darker Grotesque
    toc: false
    page-layout: article



