project:
  type: website
  output-dir: docs

website:
  title: "Morris-Sibaja"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: 
      light: solar
      dark: vapor
    css: styles.css
    toc: true
    page-layout: article



