<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.55">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="IMS">
<meta name="dcterms.date" content="2024-12-19">
<meta name="description" content="EDS 222 Final">

<title>Microplastic Distribution Analysis – Morris-Sibaja</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../images/hackerman.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../images/hackerman.png" alt="IMS logo - a triangle containg an i, m, and s" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resources.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../CV/my-cv.pdf"> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Microplastic Distribution Analysis</h1>
                  <div>
        <div class="description">
          EDS 222 Final
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Quarto</div>
                <div class="quarto-category">MEDS</div>
                <div class="quarto-category">EDS222</div>
              </div>
                  </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-heading">Affiliation</div>
    
      <div class="quarto-title-meta-contents">
      <p class="author"><a href="https://imsibaja.github.io/">IMS</a> </p>
    </div>
    <div class="quarto-title-meta-contents">
          <p class="affiliation">
              <a href="https://bren.ucsb.edu/masters-programs/master-environmental-data-science">
              MEDS
              </a>
            </p>
        </div>
    </div>

  <div class="quarto-title-meta">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 19, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data Preparation</a>
  <ul class="collapse">
  <li><a href="#load-and-clean-datasets" id="toc-load-and-clean-datasets" class="nav-link" data-scroll-target="#load-and-clean-datasets">Load and Clean Datasets</a></li>
  <li><a href="#preliminary-explorations" id="toc-preliminary-explorations" class="nav-link" data-scroll-target="#preliminary-explorations">Preliminary explorations</a>
  <ul class="collapse">
  <li><a href="#visualize-data-distribution" id="toc-visualize-data-distribution" class="nav-link" data-scroll-target="#visualize-data-distribution">Visualize Data Distribution</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#analysis-plan" id="toc-analysis-plan" class="nav-link" data-scroll-target="#analysis-plan">Analysis Plan</a>
  <ul class="collapse">
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression">Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#prepare-presenceabsence-data" id="toc-prepare-presenceabsence-data" class="nav-link" data-scroll-target="#prepare-presenceabsence-data">Prepare Presence/Absence Data</a></li>
  <li><a href="#logistic-model" id="toc-logistic-model" class="nav-link" data-scroll-target="#logistic-model">Logistic Model</a></li>
  <li><a href="#visualization" id="toc-visualization" class="nav-link" data-scroll-target="#visualization">Visualization</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#gamma-regression-microplastic-density" id="toc-gamma-regression-microplastic-density" class="nav-link" data-scroll-target="#gamma-regression-microplastic-density">Gamma Regression: Microplastic Density</a>
  <ul class="collapse">
  <li><a href="#density-by-year-model-fit" id="toc-density-by-year-model-fit" class="nav-link" data-scroll-target="#density-by-year-model-fit">Density by Year Model Fit</a></li>
  <li><a href="#parrallel-model-fit" id="toc-parrallel-model-fit" class="nav-link" data-scroll-target="#parrallel-model-fit">Parrallel Model Fit</a></li>
  <li><a href="#interaction-model-fit" id="toc-interaction-model-fit" class="nav-link" data-scroll-target="#interaction-model-fit">Interaction Model Fit</a>
  <ul class="collapse">
  <li><a href="#visualize" id="toc-visualize" class="nav-link" data-scroll-target="#visualize">Visualize</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#logistic-regression-1" id="toc-logistic-regression-1" class="nav-link" data-scroll-target="#logistic-regression-1">Logistic Regression</a></li>
  <li><a href="#gamma-regression" id="toc-gamma-regression" class="nav-link" data-scroll-target="#gamma-regression">Gamma Regression</a></li>
  </ul></li>
  <li><a href="#limitations-and-next-steps" id="toc-limitations-and-next-steps" class="nav-link" data-scroll-target="#limitations-and-next-steps">Limitations and Next Steps</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#data-availability" id="toc-data-availability" class="nav-link" data-scroll-target="#data-availability">Data Availability</a></li>
  <li><a href="#citations" id="toc-citations" class="nav-link" data-scroll-target="#citations">Citations</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>The full repository for this analysis can be found <a href="https://github.com/imsibaja/eds222-final-project">here</a>.</p>
<section id="background" class="level1">
<h1>Background</h1>
<p>Microplastics are plastic particles smaller than 5 millimeters. They are known to pose a significant threat to marine ecosystems and human health. In fact, they are ingested by marine organisms, potentially leading to starvation, entanglement, and the transfer of harmful chemicals up the food chain. 75 % of fish are estimated to have ingested microplastics, with each individual fish containing 2.5 individual particles on average (Clere et al.&nbsp;2022). These microplastics can end up on our plates, posing potential risks to human health.</p>
<p>In fact, 60% and 25% of commercial fishing are caught in the Pacific and Atlantic oceans, respectively (Rao, 2024). This is important to consider when attempting to understand the distribution patterns and trends of microplastics in our oceans. This is crucial for effective mitigation strategies, as when we begin identifying areas and periods with high microplastic concentrations, we can target cleanup efforts and implement policies to reduce plastic pollution at its source. With this information, I would like to explore the spatial and temporal trends of microplastics in the Pacific and Atlantic Ocean, the two most fished oceans in the world.</p>
<hr>
</section>
<section id="data-preparation" class="level1">
<h1>Data Preparation</h1>
<p>To begin this study, I utilized the NOAA National Centers for Environmental Information’s (NCEI) Marine Microplastics Dataset (Nyadjro, et al.&nbsp;2023) to investigate temporal and spatial trends in microplastic density. This database includes over 22,000 in-situ measured marine microplastic concentrations in our Oceans. Data is aggregated from large ocean surveys, citizen-science initiatives, and published literature. For our study, this data includes important information on microplastic concentrations, dates, and geographic locations, and was preprocessed to ensure consistency within analysis, as seen below. I used data from 2000-2020 and filtered to only the Atlantic and Pacific Oceans.</p>
<section id="load-and-clean-datasets" class="level2">
<h2 class="anchored" data-anchor-id="load-and-clean-datasets">Load and Clean Datasets</h2>
<div class="cell">
<details class="code-fold">
<summary>Load Data</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>mp <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"posts/2024-12-13-microplastic-distribution-analysis/data/Marine_Microplastics_NOAA.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Clean Data</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mp <span class="ot">&lt;-</span> mp <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Year =</span> <span class="fu">year</span>(<span class="fu">mdy_hms</span>(mp<span class="sc">$</span>Date))) <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">mdy_hms</span>(mp<span class="sc">$</span>Date)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Unit<span class="sc">==</span><span class="st">"pieces/m3"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">c</span>(<span class="st">"Oceans"</span>, <span class="st">"Regions"</span>, <span class="st">"Measurement"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>           <span class="st">"Latitude"</span>, <span class="st">"Longitude"</span>, <span class="st">"Date"</span>, <span class="st">"Year"</span>)) <span class="sc">%&gt;%</span>  </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Year <span class="sc">%in%</span> <span class="dv">2000</span><span class="sc">:</span><span class="dv">2020</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Oceans<span class="sc">!=</span><span class="st">"Arctic Ocean"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Oceans=</span><span class="fu">as.factor</span>(Oceans)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>mp_gamma <span class="ot">&lt;-</span> mp <span class="sc">%&gt;%</span> </span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(measurement), <span class="sc">!</span><span class="fu">is.na</span>(year), measurement <span class="sc">&gt;</span> <span class="dv">0</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="preliminary-explorations" class="level2">
<h2 class="anchored" data-anchor-id="preliminary-explorations">Preliminary explorations</h2>
<section id="visualize-data-distribution" class="level3">
<h3 class="anchored" data-anchor-id="visualize-data-distribution">Visualize Data Distribution</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see the distributions of microplastic densities across the Pacific and Atlantic Oceans. There are more observations in the Atlantic, however, there are very dense measurements in the Pacific.</p>
<p>Two primary questions are addressed:</p>
<ol type="1">
<li>Is the probability of encountering microplastics increasing over time?</li>
<li>When microplastics are present, how much is there?</li>
</ol>
<p>To answer these, logistic regression is used for presence/absence data, and gamma regression is applied to continuous measurement data.</p>
<hr>
</section>
</section>
</section>
<section id="analysis-plan" class="level1">
<h1>Analysis Plan</h1>
<p>Our null hypotheses are:</p>
<ul>
<li>N0: Microplastic density does not change over time in either the Atlantic or Pacific Oceans.
<ul>
<li>Failing to reject this implies that the probability of encountering microplastics in the ocean remains constant across different years.</li>
</ul></li>
<li>N0: Microplastic density does not differ across oceans/change over time.
<ul>
<li>Failing to reject this implies that neither the year of observation nor the ocean region (Atlantic or Pacific) has a significant effect on the density of microplastics.</li>
</ul></li>
</ul>
<p>Statistical models are used to analyze the data: Logistic regression to assess the probability of microplastic presence over time, gamma regression to investigate the relationship between microplastic density, time, and ocean region.</p>
<p>Logistic regression was used because the response variable is binary (presence or absence of microplastics). Gamma regression is suitable for analyzing our microplastic densities because the response variable is continuous, positive, and skewed.</p>
<hr>
<section id="logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression">Logistic Regression</h2>
<section id="probability-of-microplastic-presence" class="level4">
<h4 class="anchored" data-anchor-id="probability-of-microplastic-presence">Probability of Microplastic Presence</h4>
<ul>
<li>Model: measurement_bool ~ year</li>
<li>Formula: logit(p) = β₀ + β₁ * year</li>
</ul>
<p>Variables:</p>
<ul>
<li><p>measurement_bool: Binary variable indicating the presence or absence of microplastics.</p></li>
<li><p>year: Year of observation.</p></li>
</ul>
</section>
<section id="prepare-presenceabsence-data" class="level3">
<h3 class="anchored" data-anchor-id="prepare-presenceabsence-data">Prepare Presence/Absence Data</h3>
<div class="cell">
<details class="code-fold">
<summary>Prepare Data</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mp_logi <span class="ot">&lt;-</span> mp <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">measurement_bool =</span> <span class="fu">as.integer</span>(<span class="fu">as.logical</span>(measurement)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="logistic-model" class="level3">
<h3 class="anchored" data-anchor-id="logistic-model">Logistic Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>logi_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(measurement_bool <span class="sc">~</span> year, <span class="at">data =</span> mp_logi, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>logi_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(logi_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The slope is 0.1 and the P-Value is &lt;2e-16.The AIC is 8524"</code></pre>
</div>
</div>
</section>
<section id="visualization" class="level3">
<h3 class="anchored" data-anchor-id="visualization">Visualization</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="gamma-regression-microplastic-density" class="level1">
<h1>Gamma Regression: Microplastic Density</h1>
<ul>
<li>Models:
<ul>
<li>density ~ year</li>
<li>density ~ year + oceans</li>
<li>density ~ year * oceans</li>
</ul></li>
<li>Formula:
<ul>
<li>E(y) = exp(β₀ + β₁ * year)</li>
<li>E(y) = exp(β₀ + β₁ * year + β₂ * oceans)</li>
<li>E(y) = exp(β₀ + β₁ * year + β₂ * oceans + β₃ * year * oceans)</li>
</ul></li>
<li>Variables:
<ul>
<li>measurement: Log-linked microplastic density.</li>
<li>year: Year of observation.</li>
<li>oceans: Categorical variable representing either the Atlantic or Pacific.</li>
</ul></li>
</ul>
<section id="density-by-year-model-fit" class="level2">
<h2 class="anchored" data-anchor-id="density-by-year-model-fit">Density by Year Model Fit</h2>
<p>When plastic is collected, does its concentration change depending on the year?</p>
<section id="microplastic-density-change-over-time-across-all-oceans" class="level4">
<h4 class="anchored" data-anchor-id="microplastic-density-change-over-time-across-all-oceans">Microplastic Density Change Over Time Across all Oceans</h4>
<p>Our first model (measurement ~ year) is included in the model to investigate the effect on the year on microplastic densities. This model considers only the temporal trend, assuming the rate of change in microplastic density over time is constant across all ocean regions.</p>
<ul>
<li>Model: density ~ year</li>
<li>Formula: E(y) = exp(β₀ + β₁ * year)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Gamma regression with starting values</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>year_density <span class="ot">&lt;-</span> <span class="fu">glm</span>(measurement <span class="sc">~</span> year, </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> mp_gamma, </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">family =</span> <span class="fu">Gamma</span>(<span class="at">link =</span> <span class="st">"log"</span>),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">control =</span> <span class="fu">glm.control</span>(<span class="at">epsilon =</span> <span class="dv">1</span>))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>year_density_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(year_density)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The slope is 0.29 and the P-Value is &lt;2e-16.The AIC is 58263"</code></pre>
</div>
</div>
</section>
</section>
<section id="parrallel-model-fit" class="level2">
<h2 class="anchored" data-anchor-id="parrallel-model-fit">Parrallel Model Fit</h2>
<section id="microplastic-density-change-over-time-across-oceans" class="level4">
<h4 class="anchored" data-anchor-id="microplastic-density-change-over-time-across-oceans">Microplastic Density Change over time across Oceans</h4>
<ul>
<li>Model: density ~ year + oceans</li>
<li>Formula: E(y) = exp(β₀ + β₁ * year + β₂ * oceans)</li>
</ul>
<p>Our second model utilizes parallel terms, as it assesses microplastic density changes both over time and across different oceans, allowing for the possibility that the rate of change might differ between the Atlantic and Pacific. However, it assumes that the difference between the oceans remains constant across all years.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Gamma regression with starting values</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>year_ocean_density <span class="ot">&lt;-</span> <span class="fu">glm</span>(measurement <span class="sc">~</span> year<span class="sc">+</span>oceans, </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> mp_gamma, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">family =</span> <span class="fu">Gamma</span>(<span class="at">link =</span> <span class="st">"log"</span>),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">control =</span> <span class="fu">glm.control</span>(<span class="at">epsilon =</span> <span class="dv">1</span>))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>year_ocean_density_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(year_ocean_density)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The slope is 0.28 and the P-Value is &lt;2e-16.The AIC is 60989"</code></pre>
</div>
</div>
</section>
</section>
<section id="interaction-model-fit" class="level2">
<h2 class="anchored" data-anchor-id="interaction-model-fit">Interaction Model Fit</h2>
<section id="microplastic-density-change-over-time-by-oceans" class="level4">
<h4 class="anchored" data-anchor-id="microplastic-density-change-over-time-by-oceans">Microplastic Density Change over time by Oceans</h4>
<ul>
<li>Model: density ~ year + oceans</li>
<li>Formula: E(y) = exp(β₀ + β₁ * year + β₂ * oceans + β₃ * year * oceans)</li>
</ul>
<p>Interaction terms (measurement ~ year*oceans) are included in the model to investigate potential combined effects of time and ocean region on microplastic density. This model also allows for different rates of change in different ocean regions. But unlike the previous model, it allows the difference between the oceans to vary over time. This means that the impact of the ocean region on microplastic density might increase or decrease over the years. For example, microplastic density in the Atlantic might be increasing at a faster rate than in the Pacific in recent years.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Gamma regression with starting values</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>year_oceanXdensity <span class="ot">&lt;-</span> <span class="fu">glm</span>(measurement <span class="sc">~</span> year<span class="sc">*</span>oceans, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> mp_gamma, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">family =</span> <span class="fu">Gamma</span>(<span class="at">link =</span> <span class="st">"log"</span>),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">control =</span> <span class="fu">glm.control</span>(<span class="at">epsilon =</span> <span class="dv">1</span>))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>year_oceanXdensity_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(year_oceanXdensity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The slope is 0.24 and the P-Value is &lt;2e-16.The AIC is 63136"</code></pre>
</div>
</div>
</section>
<section id="visualize" class="level3">
<h3 class="anchored" data-anchor-id="visualize">Visualize</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="logistic-regression-1" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression-1">Logistic Regression</h2>
<section id="increasing-probability-of-microplastic-encounter" class="level4">
<h4 class="anchored" data-anchor-id="increasing-probability-of-microplastic-encounter">Increasing Probability of Microplastic Encounter</h4>
<p>The logistic regression analysis suggests a statistically significant positive relationship between time and the probability of encountering microplastics. The slope is increasing by 0.1 pieces/m3 per year and the P-Value is &lt;2e-16. This finding indicates that the likelihood of finding microplastics in the ocean is increasing over time, both in the Pacific and the Atlantic.</p>
</section>
</section>
<section id="gamma-regression" class="level2">
<h2 class="anchored" data-anchor-id="gamma-regression">Gamma Regression</h2>
<section id="temporal-and-spatial-trends-in-density" class="level4">
<h4 class="anchored" data-anchor-id="temporal-and-spatial-trends-in-density">Temporal and Spatial Trends in Density</h4>
<p>The gamma regression results reveal significant main effects of both year and ocean region on microplastic density. Specifically, the analysis indicates that microplastic density is increasing over time and is generally higher in the Pacific Ocean compared to the Atlantic Ocean. This stems from our p-value for each model at &lt;2e-16. Our slope for modeling only the year yields an increase of 0.29 microplastic pieces per m^3. Our parallel slope of the year and oceans yields an increase of 0.28 microplastic pieces per m^3. Our interactive slopes of the year and oceans yields an increase of 0.24 microplastic pieces per m^3.</p>
<p>In our models, however, we find an AIC of 58,263, 60,989, and 63,136. While relatively close to each other, we see that this gamma model does not fit the data as well as the logistic model, with an AIC of 8524. If we are to continue with this analysis, this suggests that the rate of increase in microplastic density over time is similar in both the Atlantic and Pacific Oceans. Though all of our P-Values are significant (less than 2e-16), we know to take this analysis with a grain of salt. The AICs suggest the model does not fit well on our data. We can speculate why in the next section.</p>
<hr>
</section>
</section>
</section>
<section id="limitations-and-next-steps" class="level1">
<h1>Limitations and Next Steps</h1>
<section id="limitations" class="level4">
<h4 class="anchored" data-anchor-id="limitations">Limitations</h4>
<p>The analysis presented here provides valuable insights into temporal and spatial trends in microplastic density. However, it is essential to acknowledge the limitations of the study.</p>
<p>Data Availability:</p>
<ul>
<li>The Marine Microplastics Dataset may not be fully representative of all ocean regions, and there could be gaps in data collection. Though we can see in our early distribution gap there are alot of samples, it is not randomly distributed as would be ideal.</li>
</ul>
<p>Model Complexity:</p>
<ul>
<li>While the chosen models provide a good starting point, more complex models could be explored to capture potential non-linear relationships or account for other environmental factors. There are more variables that influence the spread of microplastics besides the ocean and the year, though no extra data in our dataset was relevant to our analysis.</li>
</ul>
<p>Environmental Variability:</p>
<ul>
<li>Microplastic distribution is influenced by complex oceanographic processes, which are not fully captured in the current analysis. There is no data on seasonality, areas of where rivers feed into the ocean, and population density along the oceans.</li>
</ul>
</section>
<section id="next-steps" class="level4">
<h4 class="anchored" data-anchor-id="next-steps">Next Steps</h4>
<p>Future research could address these limitations by:</p>
<p>Expanding data collection:</p>
<ul>
<li>Gathering more data from diverse ocean regions and depths to enhance the representativeness of the analysis.</li>
</ul>
<p>Refining statistical models:</p>
<ul>
<li>Exploring alternative models, such as generalized linear mixed models (GLMMs) or time series models, to better account for data structure and environmental variability.</li>
</ul>
<p>Investigating drivers of microplastic distribution:</p>
<ul>
<li>Incorporating variables like ocean currents, wind patterns, and proximity to coastal populations to gain a deeper understanding of the factors influencing microplastic density.</li>
</ul>
<p>One idea may be to include geospatial fishing data as a way to understand how the fishery industry is contributing the microplastics in the ocean if at all. Additionally, we could model population density, proximity to major rivers, and the river water flow into the oceans. This may give us an idea on how our daily activities may be leading to mciroplastic densities.</p>
<hr>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This analysis demonstrates an increasing trend in both the probability of encountering microplastics and the density of microplastics over time. While the Pacific Ocean exhibits higher microplastic densities overall, the rate of increase over time appears to be similar across both the Atlantic and Pacific Oceans.</p>
<p>Though our p-values imply statistically significant results, our AICs should give us pause when coming to conclusions. A more robust model, like those stated in next steps, should be applied to truly understand the leading drivers of microplastics.</p>
<p>The findings underscore the urgency of addressing microplastic pollution. Targeted mitigation efforts, including reducing plastic waste at its source, improving waste management systems, and developing innovative cleanup technologies, are crucial to protect our oceans and safeguard human health. Further research, incorporating more comprehensive data and advanced modeling techniques, is essential to refine our understanding of microplastic distribution and inform effective mitigation strategies.</p>
<hr>
</section>
<section id="data-availability" class="level1">
<h1>Data Availability</h1>
<p>The NOAA National Centers for Environmental Information’s (NCEI) marine microplastics database is a crucial resource for understanding the global distribution and impact of microplastics (plastic particles less than 5mm in size). The database compiles data from various sources, including ocean surveys and citizen science initiatives, to provide a comprehensive, publicly accessible archive of microplastic concentrations in various marine environments. Its purpose is to support research, inform policy decisions, and facilitate international collaboration on addressing this widespread environmental pollutant by standardizing data collection and promoting data sharing. The database’s open-access nature is highlighted as vital for a broad assessment of the environmental problem and effective management strategies.</p>
<hr>
</section>
<section id="citations" class="level1">
<h1>Citations</h1>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Reference</th>
<th style="text-align: left;">Citation</th>
<th style="text-align: left;">Link</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Quantification and characterization of microplastics in commercial fish from southern New Zealand. Marine Pollution Bulletin, 184, 114121.</td>
<td style="text-align: left;">Clere, I. K., Ahmmed, F., Remoto, P. I., Fraser-Miller, S. J., Gordon, K. C., Komyakova, V., &amp; Allan, B. J. M. (2022).</td>
<td style="text-align: left;"><a href="https://doi.org/10.1016/j.marpolbul.2022.114121">Marine Pollution Bulletin</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">Mapped: Where the world’s fish are caught, by ocean. Visual Capitalist.</td>
<td style="text-align: left;">Rao, P. (2024, September 15).</td>
<td style="text-align: left;"><a href="https://www.visualcapitalist.com/mapped-where-the-worlds-fish-are-caught-by-ocean/">Fishing Locations</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">The NOAA NCEI marine microplastics database. Sci Data 10, 726 (2023).</td>
<td style="text-align: left;">Nyadjro, E.S., Webster, J.A.B., Boyer, T.P., Cebrian, J., Collazo, L., Kaltenberger, G., Larsen, K., Lau, Y., Mickle, P., Toft, T., Wang, Z.</td>
<td style="text-align: left;"><a href="https://doi.org/10.1038/s41597-023-02632-y">NOAA NCEI</a></td>
</tr>
</tbody>
</table>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2024, Ian Morris-Sibaja</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This website is built with <i class="fa-brands fa-github-alt" title="the alt octocat github icon" aria-label="github-alt"></i></p>
</div>
  </div>
</footer>




</body></html>